sudo: required
dist: trusty
language: generic

before_install:
  - ln -s $PWD ~/flexbe_ci && cd ~
  - ll flexbe_ci
  - cd flexbe_ci
  - ll
  - cd ~
  - source flexbe_ci/setup.bash
  - flexbe_ci_before_install indigo
  
install:
  - flexbe_ci_install
  
before_script:
  - flexbe_ci_before_script
  
script:
  - flexbe_ci_script
